In [ ]:
# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()


In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

arashnic_fitbit_path = kagglehub.dataset_download('arashnic/fitbit')
whysokaggle_fitbit_path = kagglehub.dataset_download('whysokaggle/fitbit')

print('Data source import complete.')


# **FITBIT DATA ANALYSIS**

In [ ]:
import numpy as np

!gdown https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /kaggle/working/fit.txt
100%|██████████████████████████████████████| 3.43k/3.43k [00:00<00:00, 10.2MB/s]


In [ ]:
data = np.loadtxt("/kaggle/working/fit.txt", dtype="str")
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [ ]:
# what is the shape of this data

data.shape # 96 rows/records, 6 columns/features

(96, 6)

In [ ]:
# what is the dimensionality of this data

data.ndim # this is a 2D data

2

In [ ]:
# how can we extract data

data[0] # row number 1 is extracted

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [ ]:
data[1] # row number 2 is extracted with the help of indexing

array(['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'], dtype='<U10')

In [ ]:
# we can also perform slicing

data[0:5] # first 5 records and features will be extracted

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [ ]:
# get the entire dates

data[:,0] # getting the entire dates using numpy slicing [R,C] R=rows, C=columns

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [ ]:
# let's transpose the data, meaning swapping rows to columns and vice versa

data.T.shape

(6, 96)

In [ ]:
data

date, step_count, mood, calories_burned, hours_of_sleep, activity_status = data.T

In [ ]:
# get the step counts

step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [ ]:
# noticed that step count ends with U10
# which means it's a string; so we need to convert this into integer
# so that we can perform calculations

step_count = np.array(step_count, dtype='int')
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [ ]:
# now that step count is now converted into integer
# we can perform arithmetic calculations

np.min(step_count)
np.max(step_count)
np.mean(step_count)

2935.9375

In [ ]:
# get the calories burned and convert it into integer

calories_burned = np.array(calories_burned, dtype='int')
calories_burned

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [ ]:
# get calories that is more than 100 using slicing

good_calories = calories_burned[calories_burned > 100]
good_calories

array([181, 197, 174, 223, 149, 140, 101, 152, 150, 113, 143, 125, 129,
       150, 141, 156, 181, 197, 131, 154, 137, 193, 101, 139, 164, 137,
       145, 192, 146, 234, 167, 220, 116, 131, 194, 121, 227, 125, 243,
       158, 213, 116, 129, 180, 138, 176])

Let us understand the correlation between walking and mood

In [ ]:
mood

np.unique(mood)

# let's count total number of steps people took when they were happy

happy_steps = step_count[mood == "Happy"]
h = round(np.mean(happy_steps))

# now let's get the mean of this happy steps for understanding

print(f"People took an average of {h} steps when they were Happy")

People took an average of 3393 steps when they were Happy


Let's do the same thing with sad and neutral mood


In [ ]:
sad_steps = step_count[mood == "Sad"]
s = round(np.mean(sad_steps))

neutral_steps = step_count[mood == "Neutral"]
n = round(np.mean(neutral_steps))

print(f"People took an average of {s} steps when they were Sad")
print(f"People took an average of {n} steps when they were Neutral")

People took an average of 2103 steps when they were Sad
People took an average of 3154 steps when they were Neutral


# We can conclude that the more people walk, the more they tend to be Happy

Now, let us check the correlation between mood and sleep

In [ ]:
sleep = np.array(hours_of_sleep, dtype='int')

happy_sleep = sleep[mood == 'Happy']
a = round(np.mean(happy_sleep))
print(f'Please sleep {a} hours on an average when they are Happy')

sad_sleep = sleep[mood == 'Sad']
s = round(np.mean(sad_sleep))
print(f'Please sleep {s} hours on an average when they are Sad')

neutral_sleep = sleep[mood == 'Neutral']
n = round(np.mean(neutral_sleep))
print(f'Please sleep {n} hours on an average when they are Neutral')

Please sleep 6 hours on an average when they are Happy
Please sleep 5 hours on an average when they are Sad
Please sleep 5 hours on an average when they are Neutral


# With the above analysis, we can conclude that Happy people sleep more